name: CI Base - Semana 1

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Validar estructura de carpetas
        run: |
          ls -R docs/adr/
          ls -R .github/

      - name: Simulación de Build y Lint
        run: |
          echo "Ejecutando Build..."
          echo "Ejecutando Linter..."
          echo "CI aprobada v0.1.0"
- name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir Imagen Docker (v0.1.0)
        run: |
          docker build -t mi-api:v0.1.0 .
          echo "Imagen v0.1.0 construida exitosamente"
